server:
    port: 8183
management:
    security:
        enabled: 'false'
    endpoint:
        metrics:
            enabled: 'true'
        prometheus:
            enabled: 'true'

    endpoints:
        web:
            exposure:
                include: '*'
    metrics:
        export:
            prometheus:
                enabled: 'true'

