# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
- job_name: 'prometheus'

  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  static_configs:
  - targets: ['localhost:9090']

# - job_name: 'Zuul'

#   metrics_path: '/actuator/prometheus'
#   scrape_interval: 5s
#   static_configs:
#   - targets: ['localhost:8081']

# - job_name: 'Eureka'

#   metrics_path: '/actuator/prometheus'
#   scrape_interval: 5s
#   static_configs:
#   - targets: ['localhost:8091']

# - job_name: 'Config-server'

#   metrics_path: '/actuator/prometheus'
#   scrape_interval: 5s
#   static_configs:
#   - targets: ['localhost:8092']

# - job_name: 'Mysql'

#   metrics_path: '/actuator/prometheus'
#   scrape_interval: 5s
#   static_configs:
#   - targets: ['localhost:3306']

# - job_name: 'Mongo'

#   metrics_path: '/actuator/prometheus'
#   scrape_interval: 5s
#   static_configs:
#   - targets: ['localhost:27017']

# - job_name: 'Zookeeper'

#   metrics_path: '/actuator/prometheus'
#   scrape_interval: 5s
#   static_configs:
#   - targets: ['localhost:2181']

# - job_name: 'Kafka'

#   metrics_path: '/actuator/prometheus'
#   scrape_interval: 5s
#   static_configs:
#   - targets: ['localhost:9092']


- job_name: 'Challenge-Creator'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8180']

- job_name: 'Register'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8181']

- job_name: 'File-Parser'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8182']

- job_name: 'Compilation'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8183']

- job_name: 'Authentication'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8184']

- job_name: 'User-Profile'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8185']

- job_name: 'Recommendation'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8186']

- job_name: 'Ontology'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8187']

# - job_name: 'Empty-Container'
#   metrics_path: '/actuator/prometheus'
#   scrape_interval: 5s
#   static_configs:
#   - targets: ['localhost:8188']

- job_name: 'Scoring'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8189']

- job_name: 'Voting'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:8190']

# - job_name: 'spring-boot'
#    metrics_path: '/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['172.23.239.131:8082']