server:
    port: 8186
spring:
    data:
        neo4j:
            password: root
            uri: bolt://localhost
            username: neo4j
management:
    security:
        enabled: 'false'
    endpoint:
        metrics:
            enabled: 'true'
        prometheus:
            enabled: 'true'

    endpoints:
        web:
            exposure:
                include: '*'
    metrics:
        export:
            prometheus:
                enabled: 'true'

