version: '2.0'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.23.239.131
      KAFKA_CREATE_TOPICS: "test5:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.23.239.131:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always

  mongodb:
    image: mongo:latest
    network_mode: host
    ports:
      - "27017:27017"
    container_name: test-mongo
    network_mode: host

  spring:
    image: springboot
    build: register-service/
    restart: always
    network_mode: host
    container_name: spring-app-composed
    depends_on:
      - kafka
      - mongodb
    ports:
      - 8082:8082
    expose:
      - 8082
 

